name = "RVars"
uuid = "108f709a-74fe-47a0-bf6a-d6e5c41d346f"
authors = ["Karim Naguib"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"

[extensions]
RVarsMCMCChainsExt = "MCMCChains"

[compat]
LinearAlgebra = "1"
MCMCChains = "6, 7"
Random = "1"
Statistics = "1"
julia = "1.9"

[extras]
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["MCMCChains", "Test"]
